# WordPress Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress.fullname" . }}
  #namespace: {{ .Release.Namespace | quote }}
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: {{ .Values.service.type }}

---
# MySQL Service (internal communication)
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress.fullname" . }}-mysql
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None

