apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress.fullname" . }}-wordpress
  labels:
    app.kubernetes.io/name: {{ include "wordpress.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "wordpress.name" . }}
      app.kubernetes.io/component: wordpress
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "wordpress.name" . }}
        app.kubernetes.io/component: wordpress
    spec:
      containers:
        - name: wordpress
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            - name: WORDPRESS_DB_HOST
              value: "{{ .Values.wordpress.environment.WORDPRESS_DB_HOST }}"
            - name: WORDPRESS_DB_USER
              value: "{{ .Values.wordpress.environment.WORDPRESS_DB_USER }}"
            - name: WORDPRESS_DB_PASSWORD
              value: "{{ .Values.wordpress.environment.WORDPRESS_DB_PASSWORD }}"
            - name: WORDPRESS_DB_NAME
              value: "{{ .Values.wordpress.environment.WORDPRESS_DB_NAME }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: wordpress
              mountPath: /var/www/html
      volumes:
        - name: wordpress
          persistentVolumeClaim:
            claimName: {{ include "wordpress.fullname" . }}-wordpress-pvc


